services:
  overfast-api:
    build:
      context: .
      target: ${BUILD_TARGET:-main}
    command: /code/.venv/bin/fastapi run app/main.py --port 8080 --proxy-headers
    env_file: ${APP_VOLUME_PATH:-.}/.env
    volumes:
      - static_volume:/code/static
      - ${APP_VOLUME_PATH:-/tmp}/app-logs:/code/logs
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://0.0.0.0:8080 || exit 1"]
      interval: 5s
      timeout: 5s
    networks:
      - overfast_net

  worker:
    build:
      context: .
      target: ${BUILD_TARGET:-main}
    command: crond -f
    env_file: ${APP_VOLUME_PATH:-.}/.env
    volumes:
      - ${APP_VOLUME_PATH:-/tmp}/worker-logs:/code/logs
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -i crond | grep -wv grep || exit 1"]
      interval: 5s
      timeout: 2s
    networks:
      - overfast_net

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-overfast}
      - POSTGRES_USER=${POSTGRES_USER:-overfast}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-overfast}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-overfast} -d ${POSTGRES_DB:-overfast}",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - overfast_net

  valkey:
    build:
      context: ./build/valkey
    command: sh -c "./entrypoint.sh"
    env_file: ${APP_VOLUME_PATH:-.}/.env
    # Run as privileged to allow the container to change the vm.overcommit_memory setting
    privileged: true
    restart: always
    deploy:
      resources:
        limits:
          memory: ${VALKEY_MEMORY_LIMIT:-1gb}
    volumes:
      - valkey-data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 3s
      timeout: 2s
    networks:
      - overfast_net

  nginx:
    build:
      context: ./build/nginx
    ports:
      - "${APP_PORT:-8080}:80"
    entrypoint: ["/entrypoint.sh"]
    env_file: ${APP_VOLUME_PATH:-.}/.env
    volumes:
      - static_volume:/static
    depends_on:
      overfast-api:
        condition: service_healthy
      valkey:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost || exit 1"]
      interval: 5s
      timeout: 2s
    networks:
      - overfast_net

volumes:
  static_volume:
  valkey-data:
  pg-data:

networks:
  overfast_net:
